export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const FETCH_ALL_POSTS_IN_PROGRESS = 'FETCH_ALL_POSTS_IN_PROGRESS';
export const FETCH_ALL_POSTS_SUCCESS = 'FETCH_ALL_POSTS_SUCCESS';
export const FETCH_ALL_POSTS_ERROR = 'FETCH_ALL_POSTS_ERROR';
export const FETCH_ALL_USERS_IN_PROGRESS = 'FETCH_ALL_USERS_IN_PROGRESS';
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_ERROR = 'FETCH_ALL_USERS_ERROR';
export const FETCH_USER_BY_ID = 'FETCH_USER_BY_ID';
